apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    run: petclinic
spec:
  selector:
    run: petclinic
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
